/**
 * The stylesheet, served at /assets/app.css.
 *
 * Tokens are transcribed from the Figma variable set (file Lu7cJjkrNh1YYBkYfnoXxH).
 * Figma defines the dark palette only, so the light palette here is derived:
 * the same hues, re-weighted for a light ground, with the yellow left alone
 * because it is always a fill behind dark text, never a text color.
 *
 * Fonts are self-hosted woff2 subsets under /fonts, generated by
 * scripts/build-fonts.mjs. They are NOT loaded from a font CDN. Every face
 * carries a unicode-range, so a page downloads only the scripts it renders.
 * CJK is the one gap -- those families run to megabytes even subsetted, and
 * every platform that displays CJK ships a system font for it.
 */

import { FONT_FACES } from "./font-faces"

export const STYLESHEET = `${FONT_FACES}

/* ==========================================================================
   Tokens -- dark is the base palette, matching the Figma frames.
   ========================================================================== */

:root {
  /* Surfaces */
  --bg:            #1c202f;   /* background/main */
  --surface:       #222739;   /* surface/extra */
  --surface-2:     #282d3e;   /* surface/selected */
  --callout:       #3f375d;   /* surface/callout-2 */
  --border:        #3a3e50;   /* borders/default */
  --border-soft:   #2a2f42;

  /* Ink */
  --ink:           #ffffff;   /* typography/primary */
  --ink-2:         #f1f1f3;   /* typography/secondary */
  --ink-3:         #dbdbdb;   /* typography/tertiary */
  --ink-dim:       #9aa0b8;
  --ink-faint:     #868da8;

  /* Accents */
  --yellow:        #f7e544;   /* button/primary -- fills only */
  --on-yellow:     #1c202f;
  /* Accent for TEXT and icons. The brand yellow is a fill color; on a light
     ground it fails contrast badly, so the light palette swaps in violet. */
  --accent-text:   #f7e544;
  --green:         #0eaaa0;   /* accent/green */
  --laser:         #ff8c8c;   /* accent/laser */
  --violet:        #7b6bd6;

  /* Vote states */
  --up:            #0eaaa0;
  --down:          #ff8c8c;

  /* Type */
  --sans: "Noto Sans", system-ui, -apple-system, "Segoe UI", sans-serif;
  --serif: "Noto Serif", ui-serif, Georgia, "Times New Roman", serif;
  --mono: ui-monospace, "Noto Sans Mono", "DejaVu Sans Mono", monospace;

  /* Scale, transcribed from the Figma text styles */
  --t-h1:      clamp(2.5rem, 1.4rem + 3.4vw, 4rem);
  --t-h2:      2rem;      /* Header-2-Medium 32/40 */
  --t-h3:      1.25rem;   /* Header 4 Sans 20/28 */
  --t-body:    1rem;      /* Body-lg 16/24 */
  --t-label:   0.875rem;  /* Label-md 14/14 */
  --t-small:   0.8125rem;

  --radius:    8px;
  --radius-sm: 6px;
  --radius-pill: 999px;

  --shell:     1440px;
  --gutter:    48px;

  color-scheme: dark;
}

@media (prefers-color-scheme: light) {
  :root:not([data-theme="dark"]) {
    --bg:          #f7f7fa;
    --surface:     #ffffff;
    --surface-2:   #ecedf4;
    --callout:     #ebe6f7;
    --border:      #d7d9e5;
    --border-soft: #e6e7ef;

    --ink:         #10131c;
    --ink-2:       #1c202f;
    --ink-3:       #414861;
    --ink-dim:     #5c6480;
    --ink-faint:   #6b7189;

    --yellow:      #f7e544;
    --on-yellow:   #1c202f;
    --accent-text: #4f3bbd;
    --green:       #0a807a;
    --laser:       #c9545c;
    --violet:      #5b48c0;

    --up:          #0a807a;
    --down:        #c9545c;

    color-scheme: light;
  }
}

:root[data-theme="light"] {
  --bg:          #f7f7fa;
  --surface:     #ffffff;
  --surface-2:   #ecedf4;
  --callout:     #ebe6f7;
  --border:      #d7d9e5;
  --border-soft: #e6e7ef;

  --ink:         #10131c;
  --ink-2:       #1c202f;
  --ink-3:       #414861;
  --ink-dim:     #5c6480;
  --ink-faint:   #6b7189;

  --yellow:      #f7e544;
  --on-yellow:   #1c202f;
  --accent-text: #4f3bbd;
  --green:       #0a807a;
  --laser:       #c9545c;
  --violet:      #5b48c0;

  --up:          #0a807a;
  --down:        #c9545c;

  color-scheme: light;
}

/* ==========================================================================
   Base
   ========================================================================== */

*, *::before, *::after { box-sizing: border-box; }

html { -webkit-text-size-adjust: 100%; }

body {
  margin: 0;
  background: var(--bg);
  color: var(--ink-2);
  font-family: var(--sans);
  font-size: var(--t-body);
  line-height: 1.5;
  -webkit-font-smoothing: antialiased;
}

h1, h2, h3, h4 { margin: 0; text-wrap: balance; }
p { margin: 0; }
ul, ol { margin: 0; padding: 0; }

a { color: inherit; text-decoration: none; }
a:hover { text-decoration: underline; text-underline-offset: 3px; }

:focus-visible {
  outline: 2px solid var(--accent-text);
  outline-offset: 2px;
  border-radius: 2px;
}

button { font: inherit; color: inherit; background: none; border: none; cursor: pointer; }

img, svg { max-width: 100%; }

.wrap {
  width: 100%;
  max-width: var(--shell);
  margin: 0 auto;
  padding-inline: var(--gutter);
}

.sr-only {
  position: absolute; width: 1px; height: 1px;
  padding: 0; margin: -1px; overflow: hidden;
  clip-path: inset(50%); white-space: nowrap;
}

/* ==========================================================================
   Navigation
   ========================================================================== */

.nav {
  height: 64px;
  display: flex;
  align-items: center;
  gap: 24px;
  border-bottom: 1px solid var(--border-soft);
  background: var(--bg);
  position: sticky;
  top: 0;
  z-index: 20;
}

.nav .wrap { display: flex; align-items: center; gap: 24px; }

.brand {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  font-family: var(--sans);
  font-weight: 700;
  font-size: 1.125rem;
  color: var(--ink);
  letter-spacing: -0.01em;
  white-space: nowrap;
}
.brand:hover { text-decoration: none; }
.brand .mark { width: 22px; height: 22px; flex-shrink: 0; }
.brand .dim { color: var(--ink-dim); font-weight: 400; }

.nav-links {
  display: flex;
  align-items: center;
  gap: 4px;
  list-style: none;
  margin-inline: auto;
}

.nav-link {
  display: block;
  padding: 6px 14px;
  border-radius: var(--radius-sm);
  font-size: var(--t-label);
  color: var(--ink-dim);
  transition: color .15s, background-color .15s;
}
.nav-link:hover { color: var(--ink); background: var(--surface-2); text-decoration: none; }
.nav-link[aria-current="page"] { color: var(--accent-text); background: var(--surface-2); font-weight: 700; }

.nav-actions { display: flex; align-items: center; gap: 12px; margin-left: auto; }

.theme-toggle {
  width: 32px; height: 32px;
  display: grid; place-items: center;
  border-radius: var(--radius-sm);
  color: var(--ink-dim);
}
.theme-toggle:hover { color: var(--ink); background: var(--surface-2); }
.theme-toggle .sun { display: none; }
.theme-toggle .moon { display: block; }
:root[data-theme="light"] .theme-toggle .sun { display: block; }
:root[data-theme="light"] .theme-toggle .moon { display: none; }
@media (prefers-color-scheme: light) {
  :root:not([data-theme="dark"]) .theme-toggle .sun { display: block; }
  :root:not([data-theme="dark"]) .theme-toggle .moon { display: none; }
}

/* ==========================================================================
   Buttons
   ========================================================================== */

.btn {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  padding: 10px 20px;
  border-radius: var(--radius-pill);
  font-size: var(--t-body);
  font-weight: 700;
  line-height: 1;
  white-space: nowrap;
  transition: filter .15s, background-color .15s, border-color .15s;
}
.btn:hover { text-decoration: none; }

.btn-primary { background: var(--yellow); color: var(--on-yellow); }
.btn-primary:hover { filter: brightness(1.08); }

.btn-ghost {
  border: 1px solid var(--border);
  color: var(--ink-2);
  background: transparent;
}
.btn-ghost:hover { border-color: var(--ink-dim); background: var(--surface); }

.btn-outline {
  border: 1px solid var(--accent-text);
  color: var(--accent-text);
  padding: 7px 16px;
  font-size: var(--t-label);
}
.btn-outline:hover { background: color-mix(in srgb, var(--accent-text) 12%, transparent); }

.btn-sm { padding: 7px 14px; font-size: var(--t-label); }

/* ==========================================================================
   Landing page
   ========================================================================== */

.hero {
  position: relative;
  overflow: hidden;
  background:
    radial-gradient(120% 100% at 78% 30%, rgba(123,107,214,.30), transparent 60%),
    radial-gradient(80% 90% at 12% 8%, rgba(63,55,93,.55), transparent 65%),
    linear-gradient(160deg, #232a52 0%, #1c2038 45%, var(--bg) 100%);
  border-bottom: 1px solid var(--border-soft);
}
:root[data-theme="light"] .hero {
  background:
    radial-gradient(120% 100% at 78% 30%, rgba(123,107,214,.20), transparent 60%),
    radial-gradient(80% 90% at 12% 8%, rgba(199,190,240,.5), transparent 65%),
    linear-gradient(160deg, #e8e6fb 0%, #f1f0fb 45%, var(--bg) 100%);
}
@media (prefers-color-scheme: light) {
  :root:not([data-theme="dark"]) .hero {
    background:
      radial-gradient(120% 100% at 78% 30%, rgba(123,107,214,.20), transparent 60%),
      radial-gradient(80% 90% at 12% 8%, rgba(199,190,240,.5), transparent 65%),
      linear-gradient(160deg, #e8e6fb 0%, #f1f0fb 45%, var(--bg) 100%);
  }
}

.hero .wrap {
  padding-block: 88px 96px;
  display: flex;
  flex-direction: column;
  gap: 28px;
  max-width: min(var(--shell), 100%);
  position: relative;
  z-index: 1;
}

.hero h1 {
  font-family: var(--serif);
  font-weight: 500;
  font-size: var(--t-h1);
  line-height: 1.05;
  letter-spacing: -0.02em;
  color: var(--ink);
  max-width: 15ch;
}
.hero h1 em { font-style: normal; color: var(--accent-text); display: block; }

.hero p { max-width: 46ch; color: var(--ink-3); font-size: 1.0625rem; }

.hero-actions { display: flex; flex-wrap: wrap; gap: 12px; margin-top: 4px; }

.section { padding-block: 72px; }
.section + .section { border-top: 1px solid var(--border-soft); }

.section-head {
  display: flex;
  align-items: flex-start;
  gap: 20px;
  margin-bottom: 32px;
}

/* The speech-bubble marks beside each section heading, per the Figma. */
.bubble {
  width: 44px; height: 44px;
  border: 2px solid currentColor;
  border-radius: 6px 6px 6px 0;
  flex-shrink: 0;
  position: relative;
}
.bubble::after {
  content: "";
  position: absolute;
  left: -2px; bottom: -12px;
  width: 12px; height: 12px;
  border-left: 2px solid currentColor;
  border-bottom: 2px solid currentColor;
  border-bottom-left-radius: 2px;
}
.bubble-laser { color: var(--laser); }
.bubble-violet { color: var(--violet); }
.bubble-blue { color: #4f7fe0; }

.section-head h2 {
  font-family: var(--serif);
  font-weight: 500;
  font-size: var(--t-h2);
  line-height: 1.2;
  color: var(--ink);
  max-width: 14ch;
}

.prose-block { display: flex; flex-direction: column; gap: 16px; max-width: 62ch; }
.prose-block p { color: var(--ink-3); font-size: 0.9375rem; line-height: 1.65; }
.prose-block strong { color: var(--ink); font-weight: 700; }

.split { display: grid; grid-template-columns: minmax(0, 1.15fr) minmax(0, 1fr); gap: 48px; align-items: center; }

.cards { display: grid; grid-template-columns: repeat(auto-fit, minmax(19rem, 1fr)); gap: 24px; }

.card {
  border: 1px solid var(--border);
  border-radius: var(--radius);
  padding: 24px;
  display: flex;
  flex-direction: column;
  gap: 12px;
  background: color-mix(in srgb, var(--surface) 55%, transparent);
}
.card-violet { border-color: var(--violet); }
.card-green { border-color: var(--green); }
.card .icon { color: var(--ink-dim); }
.card h3 { font-size: var(--t-body); font-weight: 700; color: var(--ink); }
.card p { font-size: 0.875rem; color: var(--ink-dim); line-height: 1.6; flex: 1; }
.card .btn { align-self: flex-start; margin-top: 4px; }

.steps { display: flex; flex-direction: column; gap: 24px; }
.step { display: grid; grid-template-columns: 34px 1fr; gap: 16px; align-items: start; }
.step .n {
  width: 34px; height: 34px;
  display: grid; place-items: center;
  border: 1px solid currentColor;
  border-radius: 6px 6px 6px 0;
  font-size: var(--t-label);
  font-weight: 700;
  font-variant-numeric: tabular-nums;
}
.step:nth-child(1) .n { color: var(--violet); }
.step:nth-child(2) .n { color: var(--green); }
.step:nth-child(3) .n { color: #4f7fe0; }
.step h3 { font-size: var(--t-body); font-weight: 700; color: var(--ink); margin-bottom: 4px; }
.step p { font-size: 0.875rem; color: var(--ink-dim); line-height: 1.6; }

.lang-section { background: var(--surface); border-block: 1px solid var(--border-soft); }
.lang-section h2 {
  font-family: var(--serif);
  font-weight: 500;
  font-size: var(--t-h2);
  color: var(--ink);
  text-align: center;
  margin-bottom: 32px;
}

.lang-grid { display: grid; grid-template-columns: repeat(auto-fill, minmax(15rem, 1fr)); gap: 12px; }

.lang-card {
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  padding: 12px 14px;
  background: var(--bg);
  display: flex;
  flex-direction: column;
  gap: 3px;
  transition: border-color .15s;
}
.lang-card:hover { border-color: var(--green); text-decoration: none; }
.lang-card .top { display: flex; align-items: baseline; gap: 8px; flex-wrap: wrap; }
.lang-card .endonym { font-weight: 700; color: var(--ink); font-size: 0.9375rem; }
.lang-card .en { font-size: var(--t-small); color: var(--ink-dim); }
.lang-card .regions { font-size: 0.75rem; color: var(--ink-faint); line-height: 1.4; }

.closing {
  background: linear-gradient(120deg, #4a2d7a 0%, #3f375d 55%, #2c2a4d 100%);
  color: #fff;
}
.closing .wrap { padding-block: 80px; display: flex; flex-direction: column; gap: 20px; }
.closing h2 {
  font-family: var(--serif);
  font-weight: 500;
  font-size: var(--t-h2);
  line-height: 1.2;
  max-width: 18ch;
  color: #fff;
}
.closing p { max-width: 54ch; font-size: 0.9375rem; line-height: 1.65; color: rgba(255,255,255,.82); }

.site-footer {
  border-top: 1px solid var(--border-soft);
  background: var(--bg);
}
.site-footer .wrap {
  padding-block: 32px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 16px;
  flex-wrap: wrap;
}
.site-footer p { font-size: var(--t-small); color: var(--ink-faint); }
.site-footer .links { display: flex; gap: 16px; }
.site-footer .links a { color: var(--ink-dim); display: grid; place-items: center; }
.site-footer .links a:hover { color: var(--ink); }

/* ==========================================================================
   App shell -- three columns, per Figma frame 21:704
   ========================================================================== */

.app {
  display: grid;
  grid-template-columns: 278px minmax(0, 1fr) 278px;
  gap: 48px;
  align-items: start;
  padding-block: 32px 64px;
}

.panel {
  background: var(--surface);
  border-radius: var(--radius);
  border: 1px solid var(--border-soft);
}

.panel-head {
  padding: 20px 20px 12px;
  font-size: var(--t-body);
  font-weight: 700;
  color: var(--ink);
}

/* Sidebar -- term list */

.term-search { padding: 0 20px 12px; }
.term-search input {
  width: 100%;
  padding: 9px 12px;
  background: var(--bg);
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  color: var(--ink-2);
  font: inherit;
  font-size: var(--t-label);
}
.term-search input::placeholder { color: var(--ink-faint); }
.term-search input:focus { outline: none; border-color: var(--yellow); }

.term-list {
  list-style: none;
  max-height: calc(100vh - 220px);
  overflow-y: auto;
  padding: 0 12px 12px;
  display: flex;
  flex-direction: column;
  gap: 2px;
}

.term-item {
  display: grid;
  grid-template-columns: 16px 1fr;
  gap: 12px;
  align-items: start;
  padding: 8px;
  border-radius: var(--radius-sm);
  font-size: var(--t-label);
  color: var(--ink-3);
  line-height: 1.45;
}
.term-item:hover { background: var(--surface-2); text-decoration: none; color: var(--ink); }
.term-item[aria-current="true"] { background: var(--surface-2); color: var(--ink); font-weight: 700; }
.term-item .status { margin-top: 2px; flex-shrink: 0; }

/* Three progress states, driven by populated-slot coverage. */
.status-none    { color: var(--ink-faint); }
.status-partial { color: var(--green); opacity: .65; }
.status-full    { color: var(--green); }

.term-count {
  padding: 10px 20px 16px;
  font-size: var(--t-small);
  color: var(--ink-faint);
  border-top: 1px solid var(--border-soft);
}

/* Main column */

.term-detail { display: flex; flex-direction: column; gap: 32px; min-width: 0; }

.eyebrow {
  font-size: var(--t-small);
  font-weight: 700;
  color: var(--ink-faint);
  letter-spacing: .04em;
}

.term-title {
  font-family: var(--serif);
  font-weight: 500;
  font-size: var(--t-h2);
  color: var(--ink);
  line-height: 1.15;
  margin-top: 4px;
}

.definition {
  background: var(--surface);
  border-radius: var(--radius-sm);
  padding: 16px 18px;
  font-size: 0.9375rem;
  line-height: 1.6;
  color: var(--ink-3);
}
.definition a { color: var(--accent-text); text-decoration: underline; text-underline-offset: 2px; }
.definition .more { display: inline-block; margin-top: 8px; color: var(--accent-text); font-size: var(--t-label); }

.block { display: flex; flex-direction: column; gap: 12px; }
.block > h2 {
  font-size: var(--t-h3);
  font-weight: 700;
  color: var(--ink);
}
.block > .lede { font-size: 0.9375rem; color: var(--ink-3); line-height: 1.6; max-width: 62ch; }
.block > .lede strong { color: var(--ink); font-weight: 700; }

.divider { height: 1px; background: var(--border-soft); border: 0; margin: 0; }

/* Slot rows -- one per applicable context */

.slots { display: flex; flex-direction: column; gap: 12px; list-style: none; }

.slot {
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  overflow: hidden;
  background: var(--surface);
}

.slot-main {
  display: flex;
  align-items: center;
  gap: 16px;
  padding: 12px 16px;
}

.slot-term {
  font-family: var(--serif);
  font-size: 1.25rem;
  color: var(--ink);
  flex: 1;
  min-width: 0;
  overflow-wrap: anywhere;
}

.slot-plurals {
  display: flex;
  flex-wrap: wrap;
  gap: 6px 18px;
  font-size: 1.0625rem;
  align-items: baseline;
}
.plural { display: inline-flex; align-items: baseline; gap: 6px; }
.plural-key {
  font-family: var(--mono);
  font-size: 0.6875rem;
  color: var(--ink-faint);
  text-transform: uppercase;
  letter-spacing: .06em;
}

.definition p { margin-block: 0 10px; }
.definition p:last-child { margin-bottom: 0; }
.definition ul, .definition ol { margin: 8px 0 8px 18px; }
.definition li { margin-bottom: 4px; }
.definition strong { color: var(--ink); }

.slot-votes { display: flex; align-items: center; gap: 12px; flex-shrink: 0; }

.vote {
  display: inline-flex;
  align-items: center;
  gap: 6px;
  padding: 4px 8px;
  border-radius: var(--radius-sm);
  font-size: var(--t-label);
  font-variant-numeric: tabular-nums;
  color: var(--ink-dim);
  transition: color .15s, background-color .15s;
}
.vote:hover { background: var(--surface-2); color: var(--ink); }
.vote[aria-pressed="true"].vote-up { color: var(--up); }
.vote[aria-pressed="true"].vote-down { color: var(--down); }

.slot-foot {
  background: var(--callout);
  padding: 6px 16px;
  display: flex;
  align-items: center;
  justify-content: space-between;
  gap: 12px;
}

.slot-label {
  font-size: var(--t-small);
  color: var(--ink-2);
  display: inline-flex;
  align-items: center;
  gap: 6px;
}

.slot-help {
  border: 0;
  background: none;
  color: var(--ink-3);
  opacity: .75;
  display: inline-grid;
  place-items: center;
  border-radius: 50%;
}
.slot-help:hover { opacity: 1; }

.slot.is-stale { border-color: var(--laser); }
.stale-flag {
  font-size: 0.75rem;
  color: var(--laser);
  display: flex;
  align-items: center;
  gap: 6px;
  padding: 6px 16px;
  border-top: 1px solid var(--border-soft);
}

.bulk-row { display: flex; justify-content: flex-end; }
.bulk-vote {
  display: inline-flex;
  align-items: center;
  gap: 8px;
  color: var(--accent-text);
  font-size: var(--t-label);
  font-weight: 700;
  padding: 6px 10px;
  border-radius: var(--radius-sm);
}
.bulk-vote:hover { background: color-mix(in srgb, var(--accent-text) 12%, transparent); }

.next-term {
  color: var(--accent-text);
  font-size: var(--t-label);
  display: inline-flex;
  align-items: center;
  gap: 6px;
  align-self: flex-start;
}

/* Suggestion form */

.suggest { display: flex; flex-direction: column; gap: 8px; }
.suggest .into { font-size: 0.9375rem; color: var(--ink-3); }
.suggest .into strong { color: var(--ink); }

.suggest-field {
  width: 100%;
  background: transparent;
  border: 0;
  border-bottom: 1px solid var(--border);
  padding: 10px 2px;
  color: var(--ink);
  font-family: var(--serif);
  font-size: 1.5rem;
}
.suggest-field::placeholder { color: var(--ink-faint); }
.suggest-field:focus { outline: none; border-bottom-color: var(--yellow); }

.suggest-reason {
  width: 100%;
  background: transparent;
  border: 0;
  border-bottom: 1px solid var(--border);
  padding: 10px 2px;
  color: var(--ink-2);
  font: inherit;
  font-size: 0.9375rem;
  resize: vertical;
  min-height: 44px;
}
.suggest-reason::placeholder { color: var(--ink-faint); }
.suggest-reason:focus { outline: none; border-bottom-color: var(--yellow); }

.suggest .btn { align-self: flex-start; margin-top: 12px; }

.hint {
  display: flex;
  align-items: flex-start;
  gap: 8px;
  font-size: var(--t-small);
  color: var(--ink-dim);
  background: var(--surface-2);
  border-radius: var(--radius-sm);
  padding: 10px 12px;
}

/* Right rail -- versions */

.rail { display: flex; flex-direction: column; gap: 12px; }
.rail h2 {
  font-size: var(--t-body);
  font-weight: 700;
  color: var(--ink);
  padding-bottom: 10px;
  border-bottom: 1px solid var(--border);
}
.rail ol { list-style: none; display: flex; flex-direction: column; gap: 10px; }
.rail li { font-size: var(--t-label); color: var(--ink-3); display: flex; gap: 8px; }
.rail time { color: var(--ink-faint); font-variant-numeric: tabular-nums; flex-shrink: 0; }
.rail .empty { font-size: var(--t-small); color: var(--ink-faint); line-height: 1.55; }

/* Language picker on the app header */

.app-bar {
  display: flex;
  align-items: center;
  gap: 16px;
  flex-wrap: wrap;
  padding-block: 20px 0;
}
.app-bar label { font-size: var(--t-label); color: var(--ink-dim); }
.lang-select {
  background: var(--surface);
  color: var(--ink-2);
  border: 1px solid var(--border);
  border-radius: var(--radius-sm);
  padding: 7px 12px;
  font: inherit;
  font-size: var(--t-label);
}
.lang-select:focus { outline: none; border-color: var(--yellow); }

/* ==========================================================================
   Context reference (the "what is prose vs ui?" page)
   ========================================================================== */

.ctx-list { display: flex; flex-direction: column; gap: 0; list-style: none; }
.ctx {
  display: grid;
  grid-template-columns: 8.5rem minmax(0, 1fr) 14rem;
  gap: 24px;
  padding: 24px 0;
  border-top: 1px solid var(--border-soft);
}
.ctx:last-child { border-bottom: 1px solid var(--border-soft); }
.ctx h3 { font-size: var(--t-body); font-weight: 700; color: var(--ink); }
.ctx .id { font-family: var(--mono); font-size: var(--t-small); color: var(--ink-faint); margin-top: 2px; }
.ctx p { font-size: 0.9375rem; color: var(--ink-3); line-height: 1.65; }
.ctx .summary { color: var(--ink); margin-bottom: 8px; }
.ctx .eg {
  background: var(--surface);
  border-radius: var(--radius-sm);
  padding: 12px 14px;
  font-size: var(--t-label);
  display: flex;
  flex-direction: column;
  gap: 6px;
  align-self: start;
}
.ctx .eg .row { display: flex; gap: 8px; justify-content: space-between; }
.ctx .eg .k { color: var(--ink-faint); font-family: var(--mono); font-size: 0.75rem; }
.ctx .eg .v { color: var(--ink); }

/* ==========================================================================
   Style guide table
   ========================================================================== */

.table-wrap { overflow-x: auto; border: 1px solid var(--border-soft); border-radius: var(--radius); }
table { border-collapse: collapse; width: 100%; font-size: var(--t-label); }
th, td { text-align: left; padding: 10px 14px; border-bottom: 1px solid var(--border-soft); }
thead th {
  background: var(--surface);
  color: var(--ink-dim);
  font-size: var(--t-small);
  font-weight: 700;
  white-space: nowrap;
  position: sticky;
  top: 0;
}
tbody tr:last-child td { border-bottom: 0; }
tbody tr:hover { background: var(--surface); }
td .term-col { color: var(--ink); font-weight: 700; }

.chip {
  display: inline-block;
  padding: 2px 8px;
  border-radius: var(--radius-pill);
  font-size: 0.75rem;
  background: var(--surface-2);
  color: var(--ink-dim);
  white-space: nowrap;
}
.chip-avoid { background: color-mix(in srgb, var(--laser) 16%, transparent); color: var(--laser); }
.chip-ok { background: color-mix(in srgb, var(--green) 16%, transparent); color: var(--green); }

/* ==========================================================================
   Responsive
   ========================================================================== */

@media (max-width: 1180px) {
  .app { grid-template-columns: 240px minmax(0, 1fr); gap: 32px; }
  .rail { grid-column: 1 / -1; }
}

@media (max-width: 900px) {
  :root { --gutter: 24px; }
  .app { grid-template-columns: minmax(0, 1fr); }
  .term-list { max-height: 320px; }
  .split { grid-template-columns: minmax(0, 1fr); gap: 32px; }
  .ctx { grid-template-columns: minmax(0, 1fr); gap: 12px; }
  .hero .wrap { padding-block: 56px 64px; }
  .section { padding-block: 48px; }
  .nav-links { display: none; }
}

@media (prefers-reduced-motion: reduce) {
  *, *::before, *::after {
    animation-duration: .01ms !important;
    transition-duration: .01ms !important;
    scroll-behavior: auto !important;
  }
}
`
