#!/usr/bin/env node
/**
 * Copies the woff2 subsets we serve into public/fonts and generates the
 * @font-face block in src/ui/font-faces.ts.
 *
 * Why generated rather than hand-written: every non-Latin script face is
 * declared under the SAME family name ("Noto Sans") with its own
 * unicode-range. The browser then picks the right file per character and
 * downloads nothing for scripts a page does not use -- a Spanish page fetches
 * the Latin subset only, while the homepage language grid pulls Arabic,
 * Bengali, Devanagari, Tamil and Telugu on demand.
 *
 * CJK is deliberately absent. Measured: Noto Sans KR alone is 2.6MB per
 * weight across 125 subsets, and adding JP/SC/TC would push the asset
 * directory past 20MB -- for four cards on a marketing grid, where the
 * English name sits right beside the endonym anyway. Every device actually
 * configured to read CJK ships a system font for it, so those fall through
 * to the system stack. Revisit if CJK translators report tofu on their own
 * language's pages, which is the case that would actually matter.
 *
 * Usage: node scripts/build-fonts.mjs
 */

import { readFileSync, writeFileSync, copyFileSync, mkdirSync, existsSync } from "node:fs"
import { dirname, join } from "node:path"
import { fileURLToPath } from "node:url"

const root = join(dirname(fileURLToPath(import.meta.url)), "..")
const outDir = join(root, "public", "fonts")
const modules = join(root, "node_modules", "@fontsource")

/** [package, family alias, css file, subsets to keep] */
const SOURCES = [
  ["noto-sans", "Noto Sans", "400.css", ["latin", "latin-ext", "cyrillic"]],
  ["noto-sans", "Noto Sans", "700.css", ["latin", "latin-ext", "cyrillic"]],
  ["noto-serif", "Noto Serif", "400.css", ["latin", "latin-ext", "cyrillic"]],
  ["noto-serif", "Noto Serif", "500.css", ["latin", "latin-ext", "cyrillic"]],
  ["noto-sans-arabic", "Noto Sans", "400.css", ["arabic"]],
  ["noto-sans-arabic", "Noto Sans", "700.css", ["arabic"]],
  ["noto-sans-bengali", "Noto Sans", "400.css", ["bengali"]],
  ["noto-sans-bengali", "Noto Sans", "700.css", ["bengali"]],
  ["noto-sans-devanagari", "Noto Sans", "400.css", ["devanagari"]],
  ["noto-sans-devanagari", "Noto Sans", "700.css", ["devanagari"]],
  ["noto-sans-tamil", "Noto Sans", "400.css", ["tamil"]],
  ["noto-sans-tamil", "Noto Sans", "700.css", ["tamil"]],
  ["noto-sans-telugu", "Noto Sans", "400.css", ["telugu"]],
  ["noto-sans-telugu", "Noto Sans", "700.css", ["telugu"]],
]

/** Pull @font-face blocks out of a fontsource stylesheet. */
function parseFaces(css) {
  const faces = []
  const blockPattern = /@font-face\s*\{([^}]*)\}/g
  let block

  while ((block = blockPattern.exec(css)) !== null) {
    const body = block[1]
    const file = body.match(/url\(\.\/files\/([^)]+\.woff2)\)/)?.[1]
    const weight = body.match(/font-weight:\s*(\d+)/)?.[1]
    const range = body.match(/unicode-range:\s*([^;]+);/)?.[1]?.trim()
    if (file && weight && range) faces.push({ file, weight, range })
  }

  return faces
}

if (!existsSync(outDir)) mkdirSync(outDir, { recursive: true })

const declarations = []
const copied = new Set()

for (const [pkg, family, cssFile, subsets] of SOURCES) {
  const pkgDir = join(modules, pkg)
  if (!existsSync(pkgDir)) {
    console.error(`missing dependency: @fontsource/${pkg} -- run pnpm install`)
    process.exit(1)
  }

  const css = readFileSync(join(pkgDir, cssFile), "utf8")

  for (const face of parseFaces(css)) {
    // fontsource names files <pkg>-<subset>-<weight>-normal.woff2
    const subset = face.file
      .replace(`${pkg}-`, "")
      .replace(`-${face.weight}-normal.woff2`, "")

    if (!subsets.includes(subset)) continue

    copyFileSync(join(pkgDir, "files", face.file), join(outDir, face.file))
    copied.add(face.file)

    declarations.push(
      `@font-face {\n` +
        `  font-family: "${family}";\n` +
        `  font-style: normal;\n` +
        `  font-weight: ${face.weight};\n` +
        `  font-display: swap;\n` +
        `  src: url("/fonts/${face.file}") format("woff2");\n` +
        `  unicode-range: ${face.range};\n` +
        `}`
    )
  }
}

const header = `/**
 * GENERATED by scripts/build-fonts.mjs -- do not edit by hand.
 *
 * Every face is declared under its display family with a unicode-range, so
 * the browser downloads only the subsets a given page actually renders.
 */

export const FONT_FACES = \``

writeFileSync(
  join(root, "src", "ui", "font-faces.ts"),
  `${header}\n${declarations.join("\n\n")}\n\`\n`
)

console.log(`wrote ${declarations.length} @font-face rules`)
console.log(`copied ${copied.size} woff2 files to public/fonts`)
